"""UX12 — engagement deliverable exports (printable HTML).

Server-renders a branded, print-ready HTML Executive Brief assembled from the
engagement's dossier + scenarios (+ BCB when present). The browser prints it to
PDF (File → Print → Save as PDF); a true server-side PDF (reportlab) is a
documented follow-up — printable HTML ships the tangible deliverable with no
new dependency and is fully testable.

The renderers are PURE (primitives in, HTML string out) so they unit-test
without a DB; the route (api/routes/engagements.py) maps the rich DB objects
onto these primitives. All dynamic text is HTML-escaped.
"""
from __future__ import annotations

import html
from typing import Optional

# ── shared chrome ───────────────────────────────────────────────────

_PRINT_CSS = """
:root { --ink:#16181d; --ink3:#5b6280; --line:#e3e5ea; --accent:#1E8A99; }
* { box-sizing: border-box; }
body { font-family: Georgia, 'Times New Roman', serif; color:#16181d;
       margin:0; padding:48px 56px; max-width:820px; }
h1 { font-size:30px; margin:0 0 4px; letter-spacing:-0.01em; }
h2 { font-size:13px; text-transform:uppercase; letter-spacing:0.12em;
     color:#6b7280; margin:28px 0 10px; font-family:'Helvetica Neue',Arial,sans-serif; }
.kicker { font-family:'Helvetica Neue',Arial,sans-serif; font-size:11px;
          letter-spacing:0.16em; text-transform:uppercase; color:#6b7280; }
.bar { height:8px; background:#eef0f3; border-radius:4px; overflow:hidden; margin:6px 0 2px; }
.bar > span { display:block; height:100%; background:#1E8A99; }
.rec { padding:14px 18px; background:#f5f8f8; border-left:3px solid #1E8A99; border-radius:0 6px 6px 0; }
ul { margin:6px 0; padding-left:18px; } li { margin:4px 0; line-height:1.5; }
.muted { color:#6b7280; font-size:12px; }
.foot { margin-top:36px; padding-top:12px; border-top:1px solid #e3e5ea;
        font-family:'Helvetica Neue',Arial,sans-serif; font-size:10.5px; color:#9aa0aa; }
@media print { body { padding:0; } @page { margin:18mm; } }
"""


def _esc(v: object) -> str:
    return html.escape(str(v if v is not None else ""))


def _pct(readiness: Optional[float]) -> str:
    if readiness is None:
        return "—"
    try:
        return f"{round(float(readiness) * 100)}%"
    except (TypeError, ValueError):
        return "—"


def render_executive_brief_html(
    *,
    engagement_name: str,
    asset: str,
    readiness: Optional[float],
    recommendation: Optional[str],
    scenarios: list[dict],
    generated_label: str,
    brief_summary: Optional[str] = None,
) -> str:
    """One-page Executive Brief. ``scenarios`` items: {name, probability}."""
    pct = _pct(readiness)
    width = pct if pct != "—" else "0%"

    rec_html = (
        f'<div class="rec">{_esc(recommendation)}</div>'
        if recommendation
        else '<p class="muted">No committed recommendation yet — derive scenarios '
             'and select a decision to populate this section.</p>'
    )

    if scenarios:
        items = "".join(
            f"<li><strong>{_esc(s.get('name'))}</strong>"
            + (f" — <span class='muted'>{_pct(s.get('probability'))} likely</span>"
               if s.get("probability") is not None else "")
            + "</li>"
            for s in scenarios
        )
        scen_html = f"<ul>{items}</ul>"
    else:
        scen_html = '<p class="muted">No scenarios derived yet.</p>'

    summary_html = (
        f"<h2>Summary</h2><p>{_esc(brief_summary)}</p>" if brief_summary else ""
    )

    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>Executive Brief — {_esc(engagement_name)}</title>
<style>{_PRINT_CSS}</style></head>
<body>
  <div class="kicker">Executive Brief · {_esc(generated_label)}</div>
  <h1>{_esc(engagement_name)}</h1>
  <div class="muted">Focal asset: {_esc(asset)}</div>

  <h2>Engagement readiness</h2>
  <div class="bar"><span style="width:{_esc(width)}"></span></div>
  <div class="muted">{_esc(pct)} of the intelligence dossier is populated.</div>

  {summary_html}

  <h2>Recommendation</h2>
  {rec_html}

  <h2>Scenarios under evaluation</h2>
  {scen_html}

  <div class="foot">
    Generated by Market Zero from the engagement's grounded dossier + scenarios.
    Every claim traces to a cited fact in the dossier. Print to PDF to share.
  </div>
</body></html>"""
